### ISSUE TITLE
Feature request: Bulk setting/unsetting of user properties

### ISSUE THREAD

**Issue by h4gen** [klaviyo/klaviyo-api-python#21]
Hi there 👋 

First of all: Thanks for the cool library 💪  Makes it really convenient to work with your API. I am a big fan!

However, I am missing two very important features right now that were somewhat besser supported with the legacy API and which I think are crucial **and I would kindly make a feature request.**

**1. Bulk setting of user properties**
Even though it was not directly supported, it was possible to bulk-set properties of users via

```
import requests
import json

API_KEY = 'APIKEY'
LIST_ID = 'LISTID'

headers = {
    'Content-Type': 'application/json',
    'api-key': API_KEY,
}

data = {
    'profiles': [
        {
            'email': 'cstestklaviyo@gmail.com',
            'properties': {
                'test_property': 'valueA',
            },
            'confirm_optin': False,
        },
        {
            'email': 'cstestklaviyo@outlook.com',
            'properties': {
                'test_property': 'valueB',
            },
            'confirm_optin': False,
        },
    ],
}

response = requests.post(f'https://a.klaviyo.com/api/v2/list/{LIST_ID}/members', headers=headers, data=json.dumps(data))
```
That was super convenient and fast. Now, If you want to set properties you can only do it per user and even though the rate limits are generous, it takes A LOT of time for a significant amount of users to assign custom properties.

**2. Unsetting of user properties**
In the legacy API it was possible to unset properties like

```
import requests
import json

api_key = ...

profile_id = ...

attribute_name = ...

url = f"https://a.klaviyo.com/api/v1/person/{profile_id}?api_key={api_key}"

data = {
    "$unset": [attribute_name],
}

response = requests.put(url, data=json.dumps(data))

print(response.text)
```
This does not seem to be possible anymore too. After sunsetting the legacy API there is no way to clean-up user profiles.

It would be great if those features would find their way again into the API, as I think they are crucial for working with user profiles.

Thank you for your attention,
Hagen

**Comment by jon-batscha** [comment]
Hi Hagen,

Thanks for reaching out, these are great suggestions!

I sent this over to our product team to add this to our roadmap, though no firm timeline yet (I’ll keep you posted as I get updates).

Regarding your first point around bulk endpoints: until we support this functionality, I recommend trying out python's native pooling functionality to speed up requests (if you haven’t already).

More details [here](https://docs.python.org/3/library/multiprocessing.html#introduction), but in short:

API requests to update_profile take 0.5 seconds round trip time. That means that if you send requests in series, you will only be able to achieve an effective rate of 120/minute. However, our rate limit for that endpoint is actually 700/minute steady. Because of this, if you parallelize your requests, you should be able to increase the request rate by a factor of ~6.

Hopefully this helps in the interim while we work on supporting the features you raised. And thanks again for the thoughtful input, we super appreciate it.


Cheers!
Jon

**Comment by h4gen** [comment]
Hi @jon-batscha 👋,

Thank you for your elaborate response and the feedback 👍 We actually tried using pooling via `async_req=True` with the library and on our own, but our measurements did not really show a significant uplift in request speed. We were never even close to hitting the 700rpm. In the end we decided that the uplift in speed did not really justify the overhead of handling the async part (i.e. waiting and checking if pool workers finished correctly).

We actually switched back this part to the legacy API and keep the fingers crossed that this is supported until the sunset of the API 🤞

Thank you,
Hagen

**Comment by odedva** [comment]
hi there 😄 
we are also using the profile update api, and the current rate limit is really low (up to 700/minute) AND high resource consumer ( api call per profile update)...it takes a lot of time if you need to update a large list\segment of users with some custom tag.
We also would be happy if we can make a bulk profiles update

**Comment by jon-batscha** [comment]
Hey,

Just wanted to let you all know that we now support `append`, `unappend`, and `unset` for `update_profile`: https://developers.klaviyo.com/en/docs/changelog_#improved-endpoints

We haven't yet implemented bulk setting of user properties, but will keep you posted once that's available.

Cheers,
Jon
