### ISSUE TITLE
_from_openapi_data() missing 1 required positional argument: 'name' on create event

### ISSUE THREAD

**Issue by vikashyadav007** [klaviyo/klaviyo-api-python#30]
```
data= {
    "data":{
        "type":"event",
        "attributes":{
            "properties":{"key": "value"},
            "metric": { 
                "data": {
                        "type": "metric",
                        "attributes": { 
                            "name": "verification_completed"
                        }
                } 
            },
            "profile":{
                "data":{
                    "type":"profile",
                    "id":"user_id",
                    "attributes": {
                        "email": "test@klaviyo.com"
                    }
                }  
            }
        }
    }
}

try:
        klaviyo.Events.create_event(event_create_query=data)
except Exception as err:
        print(err)
```

**Comment by jon-batscha** [comment]
Hey!

Thanks for reaching out, great question.

I was able to reproduce your issue, and it looks like it is due to how you are making the call, specifically:

`create_event` takes a single positional argument called `body` (though variable names for positional args are more for human readers).

Given how you have structured your code above, you can resolve the error you're seeing by updating the call to:

`klaviyo.Events.create_event(data)`

That said, I would also recommend renaming the `data` payload to `body` (strictly to help other readers of the code), and making the call as so:

`klaviyo.Events.create_event(body)`

Cheers!
Jon

**Comment by vikashyadav007** [comment]
I tried this 

### klaviyo.Events.create_event(body)

but got same response

_from_openapi_data() missing 1 required positional argument: 'name'
