### ISSUE TITLE
Need basic documentation on how Track and Identify map into this new API

### ISSUE THREAD

**Issue by savraj** [klaviyo/klaviyo-api-python#32]
Forgive me for my ignorance, but after perusing the documentation it's not clear how we would migrate the following code to this new api:

```
# old api:
import klaviyo
klaviyo_client = klaviyo.Klaviyo(
            public_token=TOKEN)
```
then 

```
klaviyo_client.Public.track(
            event_name,
            email=email,
            properties=event_properties,
            customer_properties=customer_properties)
```
or 
```
klaviyo_client.Public.identify(
            email=email,
            properties=customer_properties
        )
```

Any help? can this be added to the documentation? This all we use the python Klaviyo API for right now -- tracking events from our app that trigger flows and updating user profiles with content from our app.

**Comment by jon-batscha** [comment]
Hey Savraj,

Thanks for reaching out.

In our recent upgrade of our APIs, we split both the `track` and `identify` endpoints into two client- and server-side equivalents, each.

I am assuming you're using these serverside (but correct me otherwise).

In this case, here is how you would migrate:

1. [install the new package](https://github.com/klaviyo/klaviyo-api-python#installation)

```
pip install klaviyo-api
```

2. [instantiate the client](https://github.com/klaviyo/klaviyo-api-python#to-instantiate-the-client):
```python
from klaviyo_api import KlaviyoAPI

klaviyo = KlaviyoAPI("YOUR_API_KEY_HERE")
```

3. track -> create_event:

- [SDK function signature](https://github.com/klaviyo/klaviyo-api-python#create-event)
- [payload structure](https://developers.klaviyo.com/en/reference/create_event)

```python
body = {
  "data": {
    "type": "event",
    "attributes": {
      "properties": {},
      "metric": {
        "data": {
          "type": "metric",
          "attributes": {
            "name": "<string>",
          }
        }
      },
      "profile": {
        "data": {
          "type": "profile",
          "attributes": {
            "email": "<string>",
            "phone_number": "<string>",
            "external_id": "<string>",
            "anonymous_id": "<string>",
            "_kx": "<string>",
            "first_name": "<string>",
            "last_name": "<string>",
            "organization": "<string>",
            "title": "<string>",
            "image": "<string>",
            "location": {
              "address1": "<string>",
              "address2": "<string>",
              "city": "<string>",
              "country": "<string>",
              "latitude": "<string>",
              "longitude": "<string>",
              "region": "<string>",
              "zip": "<string>",
              "timezone": "<string>"
            },
            "properties": {}
          },
          "id": "<string>",
          "meta": {
            "patch_properties": {
              "append": {},
              "unappend": {},
              "unset": "<string>"
            }
          }
        }
      },
      "time": "<dateTime>",
      "value": "<number>",
      "unique_id": "<string>"
    }
  }
}
klaviyo.Events.create_event(body)
```

in your case, you could substitute in the values you have for `event`, `email`, `event_properties` and `customer_properties` into the above. Some reminders:
- separate the `customer_properties` into "custom_properties", which would go in `attributes.properties`, from the standard predefined customer properties, that go in `attributes` and `attributes.location`
- if your event_properties uses the deprecated `$value`, make sure to move that to `attributes.value` (more broadly, we have moved away from the `$<attribute>`) in favor of the new predefined properties, which are optional
- include `email` within `attributes`, as presumably, that's the identifier you'll be using. the predefined properties above are optional, with the exception of at least on identifier (email, phone_number, etc), so minimally, your payload could look like this:

```python
body = {
  "data": {
    "type": "event",
    "attributes": {
      "properties": event_properties,
      "metric": {
        "data": {
          "type": "metric",
          "attributes": {
            "name": event_name,
          }
        }
      },
      "profile": {
        "data": {
          "type": "profile",
          "attributes": {
            "email": email,
            "properties": customer_properties
          },
        }
      },
      "value": event_properties.get('$value'),
      "unique_id": "<string>"
    }
  }
}
```

4. identify -> create_profile:

- [SDK function signature](https://github.com/klaviyo/klaviyo-api-python#create-profile)
- [payload structure](https://developers.klaviyo.com/en/reference/create_profile)

This is similar to the create_event call above, just with a simpler payload. As above, feel free to remove any of the optional predefined attributes:

```python
body = {
	"data": {
		"type": "profile",
		"attributes": {
			"email": "<string>",
			"phone_number": "<string>",
			"external_id": "<string>",
			"first_name": "<string>",
			"last_name": "<string>",
			"organization": "<string>",
			"title": "<string>",
			"image": "<string>",
			"location": {
				"address1": "<string>",
				"address2": "<string>",
				"city": "<string>",
				"country": "<string>",
				"latitude": "<string>",
				"longitude": "<string>",
				"region": "<string>",
				"zip": "<string>",
				"timezone": "<string>"
			},
			"properties": {}
		}
	}
}

klaviyo.Profiles.create_profile(body)
```

If you have any other migration related questions, we have some resources on [this page](https://developers.klaviyo.com/en/docs/migration_resources).

Though to your point, we definitely need to add some SDK-specific migration resources; I'll add that to our team's near-term roadmap.

Definitely reach out if you run into any further issues.


(also, i see you've been a GitHub user since the year it was founded, very cool)


Cheers,
Jon
